events {
		worker_connections 1024;
}
pid logs/sitio2.pid;
http{
	server{
		listen 83;
		location / {
			root /mnt/c/Users/anton/onedrive/Desktop/Semestre_5/Desarrollo_Web/17289/nginx/3sitios/sitio2;
			index index.html;
		}
	}
}
